name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
# on:
#   schedule:
#     - cron:  '0/2 * * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Check if update available
    #   id: check
    #   uses: lucacome/docker-image-update-checker@v1
    #   with:
    #     base-image: python:3-alpine
    #     image: linux8a/shadowsocks:latest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # if: steps.check.outputs.needs-updating == 'true'

    - name: Build the Docker image
      run: |
         cd dockerfile
         docker build . --file Dockerfile --tag linux8a/shadowsocks:$(date +%s)
         tag=`docker images | grep shadowsocks | awk '{printf $1 ":" $2}'`
         docker push $tag
         docker tag $tag linux8a/shadowsocks:latest
         docker push linux8a/shadowsocks:latest
      # if: steps.check.outputs.needs-updating == 'true'
